version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 300
      runas: roots